export const Users = [
    {
      id:1,
      profilePicture: "assets/person/avatar1.jpg",
      username: "Olivia Brown",
    },
    {
      id:2,
      profilePicture: "assets/person/avatar2.jpg",
      username: "John Smith",
    },
    {
      id:3,
      profilePicture: "assets/person/avatar3.jpg",
      username: "Phil Thornton",
    },
    {
      id:4,
      profilePicture: "assets/person/avatar4.jpg",
      username: "Brad MacDonald",
    },
    {
      id:5,
      profilePicture: "assets/person/avatar5.jpg",
      username: "Zach Walker",
    },
    {
      id:6,
      profilePicture: "assets/person/avatar6.jpg",
      username: "Sarah Chen",
    },
    {
      id:7,
      profilePicture: "assets/person/avatar7.jpg",
      username: "Nadine Williams",
    },
    {
      id:8,
      profilePicture: "assets/person/avatar8.jpg",
      username: "Tristan Russell",
    },
    {
      id:9,
      profilePicture: "assets/person/avatar9.jpg",
      username: "Daniel Fish",
    },
    {
      id:10,
      profilePicture: "assets/person/avatar10.jpg",
      username: "Kate Parker",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None. A slogan taken from Ghandi’s India has never been more true than it is today. With so much hatred being spread around the world, it would make sense for everyone to love one another and live without hatred. Share this post with those close to you and let's spread the message of love together!",
      photo: "assets/post/1.jpg",
      date: "1 mins ago",
      userId: 1,
      like: 4,
      comment: 11,
    },
    {
      id: 2,
      photo: "assets/post/2.jpg",
      date: "21mins ago",
      userId: 2,
      like: 2,
      comment: 2,
    },
    {
      id: 3,
      desc: "Sometimes we need to remind ourselves how blessed our lives really are...Every moment is a fresh beginning so let’s take this chance to appreciate what we have today ❤.",
      photo: "assets/post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 10,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpg",
      date: "1 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Keep that smile on your face no matter what life throws at you!We all regret things sometimes, but it's important to make sure those regrets don't stop you from smiling when you're having a great day.",
      photo: "assets/post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "The best way to change the world is by being yourself ❤",
      photo: "assets/post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];